### ISSUE TITLE
Adding new hooks fails silently, results in partly working invisible hooks

### ISSUE THREAD

**Issue by gkdr** [KyleLNicholls/parameterized-builds#112]
Hi,

thanks for this plugin, it was easy to set up and worked as expected.
Unfortunately, when I wanted to add more hooks later on, I couldn't. I get the usual success message, but the hook ist just not there. Others seem to have simply disappeared from the list, but still work sometimes. The ones that are shown in the list still work fine.

I can't consistently produce this exception, but found it in the Bitbucket logs once and it might be related:

Plugin version: 3.2.1 (but iirc this stopped working with the previous one)
Bitbucket Server version: 5.4.1

```
 "PUT /rest/api/latest/projects/PROJECT/repos/REPO/settings/hooks/com.kylenicholls.stash.parameterized-builds:parameterized-build-hook/enabled HTTP/1.1" c.k
.s.parameterizedbuilds.item.Job IllegalArgumentException in Job.triggers: No enum constant com.kylenicholls.stash.parameterizedbuilds.item.Job.Trigger.
java.lang.IllegalArgumentException: No enum constant com.kylenicholls.stash.parameterizedbuilds.item.Job.Trigger.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.kylenicholls.stash.parameterizedbuilds.item.Job$Trigger.valueOf(Job.java:291)
        at com.kylenicholls.stash.parameterizedbuilds.item.Job$JobBuilder.triggers(Job.java:138)
        at com.kylenicholls.stash.parameterizedbuilds.helper.SettingsService.getJobs(SettingsService.java:87)
        at com.kylenicholls.stash.parameterizedbuilds.ParameterizedBuildHook.validate(ParameterizedBuildHook.java:91)
        at com.atlassian.bitbucket.setting.RepositorySettingsValidator$1.visit(RepositorySettingsValidator.java:53)
        at com.atlassian.bitbucket.setting.RepositorySettingsValidator$1.visit(RepositorySettingsValidator.java:50)
        at com.atlassian.bitbucket.scope.RepositoryScope.accept(RepositoryScope.java:26)
        at com.atlassian.bitbucket.setting.RepositorySettingsValidator.validate(RepositorySettingsValidator.java:50)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.validateSettings(DefaultRepositoryHookService.java:906)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.lambda$enable$0(DefaultRepositoryHookService.java:199)
        at java.util.Optional.ifPresent(Optional.java:159)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.enable(DefaultRepositoryHookService.java:199)
        at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
        at com.atlassian.stash.internal.rest.hook.RepositoryHookResourceHelper.enableHook(RepositoryHookResourceHelper.java:71)
        at com.atlassian.stash.internal.rest.hook.RepositoryHookRepositoryResource.enableHook(RepositoryHookRepositoryResource.java:108)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:83)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:112)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75)
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.plugin.connect.plugin.auth.oauth2.DefaultSalAuthenticationFilter.doFilter(DefaultSalAuthenticationFilter.java:69)
        at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109)
        at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32)
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:89)
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.lang.Thread.run(Thread.java:748)
        ... 284 frames trimmed
```
Reinstalling the plugin did not help as the data does not get deleted and I couldn't find it in the Bitbucket home dir to delete in manually. Maybe this could be a quick fix if you can tell me where the data is located.
Will be glad to provide more information if you can tell me where to find it.

**Comment by a-hacker** [comment]
Hi @gkdr,

That's a very strange issue you're having and looks like the job settings have been corrupted somehow. Unfortunately, that data is stored using atlassian library utils so I'm not sure where bitbucket stores that info or how to manually purge it. @KyleLNicholls, would you be able to provide any insight?

Worst-case scenario, I could probably hack a version with a "Purge all data" button for you. I'm not sure if we'd want to release that as a feature though so you'd need to package the jar yourself and upload that version. Would you feel comfortable doing this?

**Comment by gkdr** [comment]
Hi @a-hacker,

thanks for the quick response. If it's that hard to access the plugin's saved data, I do think such a button should exist somewhere hidden in the options. But in any case, yes, I can probably manage building the plugin myself from some branch containing this feature. I'd be thankful if you could put that together.

**Comment by KyleLNicholls** [comment]
It's been a while since I've looked at the bitbucket database, but there should be either a table or row with key 'com.kylenicholls.stash.parameterized-builds' that stores all the plugin settings. Since it's a hook though it might append repo information to the key (not sure). You'd have to hit the database directly to purge any corrupt data.
Purge all data button might be safer if you're not comfortable with accessing the database yourself.

**Comment by gkdr** [comment]
I did some digging in the database and found the data.

For one, there's a _plugin_setting_ table which does contain the key you mentioned, but that's only for the Jenkins login info.
Then, the _sta_repo_hook_ table contains _com.kylenicholls.stash.parameterized-builds:parameterized-build-hook_ in the _hook_key_ column, so I could get that row's _lob_id_ . In the _sta_shared_lob_ table I could then find the row matching this ID, and it seems to contain all the data as a JSON string.

To be honest, I don't feel comfortable manually deleting data from the bitbucket database, who knows where else there there could be a reference to this row. If you're interested, I can post the data for debugging purposes. I do see one item in the JSON that is not shown in the list (but it works), and adding others does in fact not do anything. Could it be that there is a limit of 10 jobs? The names are saved as _jobname-N_, where N is 0-9. The job that is invisible is number 9. Seems kinda suspicious.

**Comment by gkdr** [comment]
Okay, now instead of deleting rows I just replaced the row I found with an empty JSON object so I could start over and it seemed safe enough. Again, the 10th one I add ("jobname-9") is not visible in the interface, but exists in that row (and might work as before, I didn' test yet but it's a bug already). Trying to add any more really fails, i.e. there is no "jobname-10" in the DB.
Can you reproduce this?

What I also found when looking for that row is a second row that contained more jobs that I tried to add which were neither visible nor worked. I tried to reproduce this by adding even more jobs but was not successful.

**Comment by a-hacker** [comment]
Sorry, I haven't had an opportunity to explore this yet. It would surprise me if there was a bug causing a hard limit of 10 jobs and nobody has noticed this yet but it is certainly possible. I'll test this out when I next get the chance and update you with the results. Hopefully that will be soon.

**Comment by a-hacker** [comment]
Fixed in [3.2.3](https://github.com/KyleLNicholls/parameterized-builds/releases/tag/3.2.3)

**Comment by gkdr** [comment]
I updated the plugin and it seems to work fine now. Thank you!

**Comment by thiagolocatelli** [comment]
I know this issue is closed but where can I find the documentation on how to create jobs for this plugin using curl? Thank you

**Comment by a-hacker** [comment]
@thiagolocatelli, Right now all we have is a [Swagger spec](https://github.com/KyleLNicholls/parameterized-builds/blob/master/src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/spec.yml) for the available endpoints. Jobs are not currently configurable, only jenkins servers. Issue #105 is tracking adding rest endpoints for jobs.

**Comment by thiagolocatelli** [comment]
Thank you @a-hacker. I was able to capture the REST request from the UI (endpoint, json payload) and create a cURL request (authenticated) to Bitbucket and the jobs were created. This could be documented somewhere (maybe a section in the README.md file would be helpful)

**Comment by a-hacker** [comment]
@thiagolocatelli, I would not recommend relying on that endpoint. Because it is only meant for use by the plugin and not users, it's requirements may change at any point without warning.

**Comment by thiagolocatelli** [comment]
@a-hacker understood. Will wait for the rest endpoints. In the meantime, would you tell me which java class is handling those requests?

**Comment by a-hacker** [comment]
That's a bit tricky. It's actually a bitbucket specific endpoint that is used to save the job data. However, the data is validated by the plugin [here](https://github.com/KyleLNicholls/parameterized-builds/blob/master/src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java#L88). So while we don't control the endpoint itself, we do make sure the data is something we can work with.

**Comment by thiagolocatelli** [comment]
I figured the endpoint was specific to bitbucket `http://${bitbucket_host}/rest/api/1.0/projects/${prject_name}/repos/${repo_name}/settings/hooks/com.kylenicholls.stash.parameterized-builds:parameterized-build-hook/enabled`, I just wasnt sure where in the code it was processing the request. Thank you.
