### ISSUE TITLE
NullPointerException while trigger jenkins job

### ISSUE THREAD

**Issue by frimtec** [KyleLNicholls/parameterized-builds#189]
Since we updated our Bitbucket from 5.16.0 to 6.2.0 and therefore also updated the parameterized-builds plugin to 4.0.2 we can no longer trigger builds in jenkins:

```
2019-05-02 09:08:18,445 ERROR [http-nio-11200-exec-10] tkf9m @NTA68Ux548x64x0 cpnx8b 10.16.77.227,127.0.0.1 "POST /rest/parameterized-builds/latest/projects/SICIV/repos/epcd/triggerBuild/0/feature%252FSICIV-6696-cr-32-69-bulk-change-epcd-anlegen-qr-iid-fis-verknupfung-zu-konto HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: null
java.lang.NullPointerException: null
        at com.kylenicholls.stash.parameterizedbuilds.ciserver.Jenkins.triggerJob(Jenkins.java:307)
        at com.kylenicholls.stash.parameterizedbuilds.rest.BuildResource.triggerBuild(BuildResource.java:102)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
        at com.atlassian.bitbucket.internal.xcode.web.XcodeUserAgentFilter.doFilter(XcodeUserAgentFilter.java:36)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:85)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:112)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75)
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.plugin.connect.plugin.auth.oauth2.DefaultSalAuthenticationFilter.doFilter(DefaultSalAuthenticationFilter.java:69)
        at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109)
        at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:37)
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
        at com.atlassian.bitbucket.internal.scm.git.lfs.servlet.filter.GitLfsLockingFilter.doFilter(GitLfsLockingFilter.java:50)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:87)
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.lang.Thread.run(Thread.java:834)
        ... 244 frames trimmed
```

Setup information:
- _Parameterized Builds for Jenkins_ plugin version: 4.0.2
- _Bitbucket_ version: 6.2.0
- _Jenkins_ Version: 2.164.1

**Comment by krm1** [comment]
After the update you have to select your jenkins instance in the hook configuration menue for each trigger. Might be that issue.

**Comment by frimtec** [comment]
The jenkins instance configuration is available and correct. 
When I press the "Test Jenkins Settings" it says: "Connection successful".

**Comment by krm1** [comment]
Test jenkins Settings is another menue, I meant here:
![grafik](https://user-images.githubusercontent.com/25386454/57120262-7cdaf580-6d70-11e9-9b22-6f713a9aac57.png)

**Comment by frimtec** [comment]
Oh yes, your right, I have overseen this new option.
Many thanks for your help, all works fine again.

**Comment by a-hacker** [comment]
Hi @frimtec, I'm glad you got it working. I should have written an upgrade guide when the new version was released. I'll make sure to get that done in the next few days so that others do not run into the same issues.
