### ISSUE TITLE
Test Jenkins Settings does not use saved token

### ISSUE THREAD

**Issue by h2oboy** [KyleLNicholls/parameterized-builds#219]
Hi,

- _Parameterized Builds for Jenkins_ plugin version: **4.0.5**
- _Bitbucket_ version: Local Windows Server **v6.3.2**
- _Jenkins_ Version: Local Windows Server **2.185**
- Detailed description of the issue

**I have the following issue**

I noticed that somehow Jenkins Settings does not save the Token. I added the token once and Save-> Test Jenkins Settings. The plugin was able to communicate with Jenkins . If I come back to Jenkins Settings and I try to test Jenkins Settings the connection fails. Seams like the token was not saved.

**Comment by a-hacker** [comment]
Per Gitter converstain 

> I believe that the token is saved. However, when the page is rerendered the token is not populated on the page. This is because the api token is a secret and should be treated as such. The test settings button uses what's currently on the page so it will be missing the token and fail as you've observed.

The test settings should be smart enough to handle this though so I'm leaving this issue open to track that problem.

**Comment by damyan** [comment]
Same issue here using 4.0.7 installed on Bitbucket Server 4.7.1
--
   Damyan

**Comment by a-hacker** [comment]
@damyan, plugin versions 4.X.X only support Bitbucket Server 6. Bitbucket Server 4 versions have not been supported for a long time and I would be surprised if the plugin worked at all on such an old version. Did you mean 6.7.1?

To be clear though, this is not an issue with the token not being set. It is being set, it's just not used properly when pressing the "Test Jenkins Settings" button. If you are getting 401's then you should check that the token you are using is correct using curl and that you've indicated whether csrf protection is enabled.

**Comment by damyan** [comment]
> @damyan, plugin versions 4.X.X only support Bitbucket Server 6. Bitbucket Server 4 versions have not been supported for a long time and I would be surprised if the plugin worked at all on such an old version. Did you mean 6.7.1?
> 
Sorry about the misleading info. I meant 6.7.1, sure.

> To be clear though, this is not an issue with the token not being set. It is being set, it's just not used properly when pressing the "Test Jenkins Settings" button. If you are getting 401's then you should check that the token you are using is correct using curl and that you've indicated whether csrf protection is enabled.
> 
You are right, it was just the test button which returns 401s. The jobs seem to get triggered, though.
When debugging the test button issue yesterday, we saw a lot of null pointer exceptions in the bitbucket log. We keep getting them, I couldn't yet spot the action leading to the NPE. Do you have an idea if that might be somehow related?
BB log callstack:
2019-10-10 09:26:47,761 ERROR [threadpool:thread-2]  c.a.s.i.c.DefaultTransferableStateManager Error while processing asynchronous task
java.lang.NullPointerException: null
	at com.kylenicholls.stash.parameterizedbuilds.ciserver.Jenkins.triggerJob(Jenkins.java:307)
	at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.BaseHandler.triggerJenkins(BaseHandler.java:41)
	at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.BaseHandler.run(BaseHandler.java:35)
	at com.kylenicholls.stash.parameterizedbuilds.eventHandlers.PRHandler.run(PRHandler.java:53)
	at com.kylenicholls.stash.parameterizedbuilds.PullRequestHook.lambda$0(PullRequestHook.java:110)
	at com.atlassian.stash.internal.concurrent.DefaultTransferableStateManager$StateTransferringRunnable.run(DefaultTransferableStateManager.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	... 1 frame trimmed

**Comment by a-hacker** [comment]
Fixed in 4.0.8

**Comment by a-hacker** [comment]
@damyan, if you are still receiving null pointer exceptions after upgrading, please open a new issue.
