### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mabushey** [KyleLNicholls/parameterized-builds#99]
We "upgraded" to Bitbucket 5.4.0, and the automatic building of branches and PRs stopped. We're using a multi-branch pipeline. It looks like this Bitbucket plugin is the only one that works with 5.4.0, so I uninstalled "bitbucket-webhook" and installed "Parameterized Builds for Jenkins". Is it compatible with the Jenkins  "Bitbucket Branch Source Plugin"?

Under my repo: Repository settings -> Hooks -> Parameterized Builds for Jenkins is enabled

Besides Bitbucket not kicking off any Jenkins jobs, any manually triggered jobs result in:
```
 > git rev-list 7108fa944d0290fa15c2ee950a701828dfeb0ab0 # timeout=10
[Bitbucket] Notifying commit build result
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
java.lang.AbstractMethodError: org.jenkinsci.plugins.pipeline.modeldefinition.validator.ModelValidatorImpl.validateElement(Lorg/jenkinsci/plugins/pipeline/modeldefinition/ast/ModelASTStage;Z)Z
	at org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage.validate(ModelASTStage.java:78)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStages.validate(ModelASTStages.java:41)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStages.validate(ModelASTStages.java:35)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef.validate(ModelASTPipelineDef.java:64)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef$validate.call(Unknown Source)
	at org.jenkinsci.plugins.pipeline.modeldefinition.parser.ModelParser.parse(ModelParser.groovy:204)
	at org.jenkinsci.plugins.pipeline.modeldefinition.parser.ModelParser$parse.callCurrent(Unknown Source)
	at org.jenkinsci.plugins.pipeline.modeldefinition.parser.ModelParser.parse(ModelParser.groovy:91)
	at org.jenkinsci.plugins.pipeline.modeldefinition.parser.GroovyShellDecoratorImpl$1.call(GroovyShellDecoratorImpl.java:46)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:129)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:123)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:517)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:480)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:269)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Finished: FAILURE
```

Any idea? I'm having a hard time trying to understand the Docs. I wish there was a test button to determine if the plugin is configured correctly.

**Comment by a-hacker** [comment]
Hi @mabushey,

Currently this plugin does not have very good native support for multibranch plugins. This is a feature I have been working on. You can track the issue at #93. I've been crunched for time the last few weeks so I haven't gotten much done but will hopefully finish that up in the next few weeks.

I also have not tested against 5.4.0 yet. However, the plugin works fine for earlier versions of 5.X. I don't suspect that 5.4.0 is the problem but it could be. Did you have the plugin working on an earlier version of Bitbucket or did you just install this plugin after upgrading and found it to not work as expected?

If you would like to test your configuration, I find it easiest to create a quick dummy jenkins job and set up a manual trigger against it. If your configuration is set up correctly, running the trigger should cause a build of the jenkins job. That being said, a test button in the Jenkins Settings would be a great idea to help check that settings are configured correctly. If you create a separate issue for it, I'll look into it when I find some time.

**Comment by mabushey** [comment]
Thanks for your response @a-hacker. :) 

I upgraded `Pipeline: Declarative` and `Pipeline: Declarative Extension Points API` from 1.1.9 to 1.2.2 and builds started kicking off in Jenkins. I think there was a version incompatibility with the other Jenkins plugins that were causing it to abort. This `Parameterized Builds` plugin seems to be working now.

I'll keep my eye on #93. Thanks again!
